// products.js — Single source of truth for all product data
// Edit this file to add, remove, or modify products.
// All files (index.html, app.js) pull from window.PRODUCTS.

window.PRODUCTS = [
  {
    id: 1,
    slug: "kursi-tamu-jati-minimalis",
    name: "Kursi Tamu Jati Minimalis",
    category: "Kursi",
    price: "Rp 1.250.000",
    description: "Kursi jati solid dengan desain minimalis, cocok untuk ruang tamu modern dan tahan digunakan dalam jangka panjang.",
    material: "Kayu jati solid",
    finish: "Natural matte",
    dimensions: "75 × 70 × 95 cm",
    badge: "Terlaris",
    emoji: "🪑",
    bg: "linear-gradient(135deg,#f0e6d3,#d9c9b0)",
    thumbnail: "images/kursi-tamu-jati-minimalis.jpg",
    model_glb:  "models/kursi-tamu-jati-minimalis.glb",
    model_usdz: "models/kursi-tamu-jati-minimalis.usdz",
    whatsapp_message: "Halo Mebel Jati Nusantara, saya tertarik dengan *Kursi Tamu Jati Minimalis* (Rp 1.250.000). Bisa info lebih lanjut mengenai ketersediaan dan pengiriman?"
  },
  {
    id: 2,
    slug: "meja-kopi-industrial",
    name: "Meja Kopi Kayu Industrial",
    category: "Meja",
    price: "Rp 980.000",
    description: "Meja kopi dengan kombinasi kayu dan aksen industrial yang memberikan tampilan hangat dan modern.",
    material: "Kayu solid & rangka metal",
    finish: "Dark walnut",
    dimensions: "100 × 55 × 45 cm",
    badge: null,
    emoji: "🪵",
    bg: "linear-gradient(135deg,#e8dcc6,#c9b890)",
    thumbnail: "images/meja-kopi-industrial.jpg",
    model_glb:  "models/meja-kopi-industrial.glb",
    model_usdz: "models/meja-kopi-industrial.usdz",
    whatsapp_message: "Halo Mebel Jati Nusantara, saya tertarik dengan *Meja Kopi Kayu Industrial* (Rp 980.000). Apakah masih tersedia?"
  },
  {
    id: 3,
    slug: "lemari-pajangan-serbaguna",
    name: "Lemari Pajangan Serbaguna",
    category: "Lemari",
    price: "Rp 2.400.000",
    description: "Lemari multifungsi untuk menyimpan dan memajang dekorasi, buku, atau koleksi pribadi dengan tampilan rapi.",
    material: "Kayu mahoni",
    finish: "Light oak",
    dimensions: "120 × 40 × 180 cm",
    badge: "Pilihan Editor",
    emoji: "🚪",
    bg: "linear-gradient(135deg,#e0d4c0,#c8b89a)",
    thumbnail: "images/lemari-pajangan-serbaguna.jpg",
    model_glb:  "models/lemari-pajangan-serbaguna.glb",
    model_usdz: "models/lemari-pajangan-serbaguna.usdz",
    whatsapp_message: "Halo Mebel Jati Nusantara, saya tertarik dengan *Lemari Pajangan Serbaguna* (Rp 2.400.000). Bisa kirim foto terbaru produk ini?"
  },
  {
    id: 4,
    slug: "rak-buku-modern",
    name: "Rak Buku Dinding Modern",
    category: "Rak",
    price: "Rp 720.000",
    description: "Rak buku hemat ruang dengan desain modern yang cocok untuk ruang kerja, kamar tidur, atau ruang belajar.",
    material: "Kayu engineered premium",
    finish: "Natural wood",
    dimensions: "80 × 25 × 160 cm",
    badge: null,
    emoji: "📚",
    bg: "linear-gradient(135deg,#dde8d3,#b8c9a0)",
    thumbnail: "images/rak-buku-modern.jpg",
    model_glb:  "models/rak-buku-modern.glb",
    model_usdz: "models/rak-buku-modern.usdz",
    whatsapp_message: "Halo Mebel Jati Nusantara, saya tertarik dengan *Rak Buku Dinding Modern* (Rp 720.000). Apakah bisa pesan dalam warna custom?"
  },
  {
    id: 5,
    slug: "sofa-dua-dudukan-premium",
    name: "Sofa Dua Dudukan Premium",
    category: "Sofa",
    price: "Rp 3.500.000",
    description: "Sofa dua dudukan dengan busa empuk dan desain elegan yang cocok untuk rumah bergaya modern minimalis.",
    material: "Kayu rangka, busa premium, kain upholstery",
    finish: "Beige soft",
    dimensions: "160 × 85 × 90 cm",
    badge: "Premium",
    emoji: "🛋️",
    bg: "linear-gradient(135deg,#ece8d8,#d4c9a8)",
    thumbnail: "images/sofa-dua-dudukan-premium.jpg",
    model_glb:  "models/sofa-dua-dudukan-premium.glb",
    model_usdz: "models/sofa-dua-dudukan-premium.usdz",
    whatsapp_message: "Halo Mebel Jati Nusantara, saya tertarik dengan *Sofa Dua Dudukan Premium* (Rp 3.500.000). Ada pilihan warna atau kain lain?"
  },
  {
    id: 6,
    slug: "meja-kerja-jati",
    name: "Meja Kerja Kayu Jati",
    category: "Meja",
    price: "Rp 1.850.000",
    description: "Meja kerja ergonomis dengan tampilan hangat, cocok untuk kantor rumahan atau ruang belajar.",
    material: "Kayu jati & lapisan pelindung",
    finish: "Warm brown",
    dimensions: "120 × 60 × 75 cm",
    badge: null,
    emoji: "🖥️",
    bg: "linear-gradient(135deg,#f0e0c8,#d8b890)",
    thumbnail: "images/meja-kerja-jati.jpg",
    model_glb:  "models/meja-kerja-jati.glb",
    model_usdz: "models/meja-kerja-jati.usdz",
    whatsapp_message: "Halo Mebel Jati Nusantara, saya tertarik dengan *Meja Kerja Kayu Jati* (Rp 1.850.000). Berapa lama waktu produksinya?"
  },
  {
    id: 7,
    slug: "hiasan-dinding-ukir",
    name: "Hiasan Dinding Kayu Ukir",
    category: "Dekorasi",
    price: "Rp 450.000",
    description: "Hiasan dinding berbahan kayu jati dengan ukiran motif nusantara. Sentuhan budaya lokal untuk ruang yang lebih hidup.",
    material: "Kayu jati ukir",
    finish: "Natural oiled",
    dimensions: "60 × 5 × 40 cm",
    badge: null,
    emoji: "🪴",
    bg: "linear-gradient(135deg,#e8e0d0,#c9b898)",
    thumbnail: "images/hiasan-dinding-ukir.jpg",
    model_glb:  "models/hiasan-dinding-ukir.glb",
    model_usdz: "models/hiasan-dinding-ukir.usdz",
    whatsapp_message: "Halo Mebel Jati Nusantara, saya tertarik dengan *Hiasan Dinding Kayu Ukir* (Rp 450.000). Apakah motif bisa dipesan custom?"
  },
  {
    id: 8,
    slug: "kursi-makan-sonokeling",
    name: "Kursi Makan Sonokeling",
    category: "Kursi",
    price: "Rp 890.000",
    description: "Kursi makan dari kayu sonokeling dengan warna gelap alami yang mewah. Eksklusif dan tahan lama.",
    material: "Kayu sonokeling solid",
    finish: "Dark natural",
    dimensions: "45 × 50 × 90 cm",
    badge: "Baru",
    emoji: "🍽️",
    bg: "linear-gradient(135deg,#d8ccb8,#b8a888)",
    thumbnail: "images/kursi-makan-sonokeling.jpg",
    model_glb:  "models/kursi-makan-sonokeling.glb",
    model_usdz: "models/kursi-makan-sonokeling.usdz",
    whatsapp_message: "Halo Mebel Jati Nusantara, saya tertarik dengan *Kursi Makan Sonokeling* (Rp 890.000). Apakah bisa pesan dalam set 4 atau 6 kursi?"
  }
];

// Quick lookup helpers
window.getProductById   = (id)   => window.PRODUCTS.find(p => p.id   === id);
window.getProductBySlug = (slug) => window.PRODUCTS.find(p => p.slug === slug);
